name: "1"
description: "234"
title: "5"
labels: "6"
assignees: "7"
body:
        - type: input
          id: "12"
          attributes:
                  label: "8"
                  description: "10"
                  placeholder: "11"
                  value: "9"
          validations:
                  required: true
        - type: markdown
          attributes:
                  value: |
                          13
        - type: textarea
          id: "19"
          attributes:
                  label: "14"
                  description: "16"
                  placeholder: |
                          17
                  value: |
                          15
                  render: 18
          validations:
                  required: true
        - type: dropdown
          id: "24"
          attributes:
                  label: "20"
                  description: "23"
                  multiple: false
                  options:
                          - 21
                          - 22
          validations:
                  required: true
        - type: checkboxes
          id: "28"
          attributes:
                  label: "25"
                  description: "27"
                  options:
                          - label: "26"
                            required: true
        - type: input
          id: "e"
          attributes:
                  label: "a"
                  description: "c"
                  placeholder: "d"
                  value: "b"
          validations:
                  required: true
        - type: markdown
          attributes:
                  value: |
                          f
        - type: textarea
          id: "l"
          attributes:
                  label: "g"
                  description: "i"
                  placeholder: |
                          j
                  value: |
                          h
                  render: k
          validations:
                  required: true
        - type: dropdown
          id: "q"
          attributes:
                  label: "m"
                  description: "p"
                  multiple: false
                  options:
                          - n
                          - o
          validations:
                  required: true
        - type: checkboxes
          id: "u"
          attributes:
                  label: "r"
                  description: "t"
                  options:
                          - label: "s"
                            required: true
