name: "1"
description: "234"
title: "5"
labels: "68"
assignees: "7"
body:
        - type: input
          id: 5
          attributes:
                  label: "1"
                  description: "3"
                  placeholder: "4"
                  value: "2"
          validations:
                  required: true
        - type: markdown
          attributes:
                  value: |
                          6
        - type: textarea
          id: 12
          attributes:
                  label: "7"
                  description: "9"
                  placeholder: |
                          10
                  value: |
                          8
                  render: 11
          validations:
                  required: true
        - type: dropdown
          id: 17
          attributes:
                  label: "13"
                  description: "16"
                  multiple: false
                  options:
                          - 14
                          - 15
          validations:
                  required: true
        - type: checkboxes
          id: 21
          attributes:
                  label: "18"
                  description: "20"
                  options:
                          - label: "19"
                            required: true
