name: "123"
description: "456"
title: "7"
labels: "8"
assignees: "9"
body:
        - type: input
          id: "14"
          attributes:
                  label: "10"
                  description: "12"
                  placeholder: "13"
                  value: "11"
          validations:
                  required: true
        - type: markdown
          attributes:
                  value: |
                          15
        - type: textarea
          id: "21"
          attributes:
                  label: "16"
                  description: "18"
                  placeholder: |
                          19
                  value: |
                          17
                  render: 20
          validations:
                  required: true
        - type: dropdown
          id: "26"
          attributes:
                  label: "22"
                  description: "25"
                  multiple: false
                  options:
                          - 23
                          - 24
          validations:
                  required: true
        - type: checkboxes
          id: "30"
          attributes:
                  label: "27"
                  description: "29"
                  options:
                          - label: "28"
                            required: true
        - type: input
          id: "e"
          attributes:
                  label: "a"
                  description: "c"
                  placeholder: "d"
                  value: "b"
          validations:
                  required: true
        - type: markdown
          attributes:
                  value: |
                          f
        - type: textarea
          id: "l"
          attributes:
                  label: "g"
                  description: "i"
                  placeholder: |
                          j
                  value: |
                          h
                  render: k
          validations:
                  required: true
        - type: dropdown
          id: "q"
          attributes:
                  label: "m"
                  description: "p"
                  multiple: false
                  options:
                          - n
                          - o
          validations:
                  required: true
        - type: checkboxes
          id: "u"
          attributes:
                  label: "r"
                  description: "t"
                  options:
                          - label: "s"
                            required: true
